const gulp = require('gulp')
const babel = require('gulp-babel')
const plumber = require('gulp-plumber')
// const replace = require('gulp-replace')
// const sourcemaps = require('gulp-sourcemaps')
// const uglify = require('gulp-uglify')

gulp.task('build', function() {
  return gulp.src("./src/**/*.js")
    // .pipe(sourcemaps.init())
    .pipe(plumber())
    .pipe(babel())
    // .pipe(uglify().on('error', console.log))
    // .pipe(sourcemaps.write('./maps'))
    .pipe(gulp.dest("./dist"))
})
